g++ 4.4 fix: Add -Wno-invalid-offsetof switch
TODO:
 - Validate that this still produces correct code.
 - Find a better place to put the switch in the Makefile

Works around:

cc1plus: warnings being treated as errors
In file included from /home/emaisin/src/binutils-gdb/gdb/target.h:74,
                 from /home/emaisin/src/binutils-gdb/gdb/inferior.h:38,
                 from /home/emaisin/src/binutils-gdb/gdb/amd64-tdep.c:31:
/home/emaisin/src/binutils-gdb/gdb/btrace.h: In function ‘size_t VEC_btrace_insn_s_embedded_size(int)’:
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: invalid access to non-static data member ‘VEC_btrace_insn_s::vec’  of NULL object
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: (perhaps the ‘offsetof’ macro was used incorrectly)
/home/emaisin/src/binutils-gdb/gdb/btrace.h: In function ‘VEC_btrace_insn_s* VEC_btrace_insn_s_alloc(int)’:
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: invalid access to non-static data member ‘VEC_btrace_insn_s::vec’  of NULL object
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: (perhaps the ‘offsetof’ macro was used incorrectly)
/home/emaisin/src/binutils-gdb/gdb/btrace.h: In function ‘VEC_btrace_insn_s* VEC_btrace_insn_s_copy(VEC_btrace_insn_s*)’:
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: invalid access to non-static data member ‘VEC_btrace_insn_s::vec’  of NULL object
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: (perhaps the ‘offsetof’ macro was used incorrectly)
/home/emaisin/src/binutils-gdb/gdb/btrace.h: In function ‘VEC_btrace_insn_s* VEC_btrace_insn_s_merge(VEC_btrace_insn_s*, VEC_btrace_insn_s*)’:
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: invalid access to non-static data member ‘VEC_btrace_insn_s::vec’  of NULL object
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: (perhaps the ‘offsetof’ macro was used incorrectly)
/home/emaisin/src/binutils-gdb/gdb/btrace.h: In function ‘int VEC_btrace_insn_s_reserve(VEC_btrace_insn_s**, int, const char*, unsigned int)’:
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: invalid access to non-static data member ‘VEC_btrace_insn_s::vec’  of NULL object
/home/emaisin/src/binutils-gdb/gdb/btrace.h:84: error: (perhaps the ‘offsetof’ macro was used incorrectly)

Reference: https://sourceware.org/ml/gdb/2015-12/msg00014.html