Extract register_reader and register_readwriter interfaces from regcache
In the following patch, we make gdbarch pseudo-registers hooks read and
write required registers from a frame instead of from the current
regcache.  To avoid having to change the implementation of all
architectures to use a different interface, we can re-use the regcache
interface.

This patch extracts two interfaces, register_reader and
register_readwriter, and make respectively readable_regcache and
regcache inherit from them.  register_reader is "something from which
you can read register values from".  It can of course be a regcache, but
it will also be (in the following patch) something that unwinds
registers for a particular frame.  As you would expect,
register_readwriter is "something you can read and write registers
from/to".

Some notes about the implementation.  This results in diamond
inheritance: regcache inherits from both readable_regcache and
register_readwriter, which both inherit from register_reader.  It is
therefore necessary to use virtual inheritance (use "public virtual"),
otherwises we end up with errors like:

  /home/emaisin/src/binutils-gdb/gdb/regcache.c:210:20: error: request
  for member ‘cooked_read’ is ambiguous

Also, the raw_read method in readable_regcache hides the raw_read
template method in register_reader.  So it's necessary to use "using
register_reader::raw_read" so that clients of readable_regcache are able
to call register_reader's raw_read.  Same thing for some cooked_read,
raw_write and cooked_write.

All corresponding gdbarch hooks are updated to use register_reader or
register_readwriter instead of readable_regcache and regcache, but
otherwise they are not changed.

With this patch, no behavior change is expected.

gdb/ChangeLog:

	* regcache.h (struct register_reader,
	struct register_readwriter): Forward-declare.
	(regcache_raw_read_signed, regcache_raw_write_signed,
	regcache_raw_write_unsigned, regcache_cooked_read_signed,
	regcache_cooked_read_unsigned, regcache_cooked_write_signed,
	regcache_cooked_write_unsigned): Use
	register_reader/register_readwriter.
	(struct register_reader, struct register_readwriter): New.
	(class readable_regcache): Extend register_reader.
	<arch>: New.
	<raw_read (int regnum, gdb_byte *buf)>: Override parent method.
	<raw_read (int regnum, T *val)>: Move to register_reader.
	<cooked_read (int regnum, gdb_byte *buf)>: Override parent
	method.
	<cooked_read (int regnum, T *val)>: Move to register_reader.
	<cooked_read_part, cooked_read_value, read_part>: Move to
	register_reader.
	<raw_update>: New.
	(class regcache): Extend register_readwriter.
	<arch, invalidate>: New.
	<raw_write (int regnum, const gdb_byte *buf)>: Override parent
	method.
	<raw_write (int regnum, T val)>: Move to register_readwriter.
	<cooked_write (int regnum, const gdb_byte *buf)>: Override
	parent method.
	<cooked_write (int regnum, T val)>: Move to register_readwriter.
	<raw_write_part, cooked_write_parti, write_part>: Move to
	register_readwriter.
	* regcache.c (readable_regcache::raw_read): Move asserts here.
	Rename other overload to ...
	(register_reader::raw_read): ... this, adjust.
	(regcache_raw_read_signed): Change regcache parameter to
	readable_regcache.
	(regcache_raw_write_signed): Change regcache parameter to
	register_readwriter.
	(regcache::raw_write): Rename to ...
	(register_readwriter::raw_write): ... this, adjust.
	(regcache_raw_write_unsigned): Change regcache parameter to
	register_readwriter.
	(readable_regcache::cooked_read_value): Rename to ...
	(register_reader::cooked_read_value): ... this, and adjust.
	(regcache_cooked_read_signed): Change regcache parameter type to
	register_reader.
	(readable_regcache::cooked_read): Rename to ...
	(register_reader::cooked_read): ... this, adjust.
	(regcache_cooked_read_unsigned): Replace regcache parameter type
	to register_reader.
	(regcache_cooked_write_signed): Replace regcache parameter type
	to register_readwriter.
	(regcache::cooked_write): Rename to ...
	(register_readwriter::cooked_write): ... this, adjust.
	(regcache_cooked_write_unsigned): Replace regcache parameter
	type to register_readwriter.
	(readable_regcache::read_part): Rename to ...
	(register_reader::read_part): ... this.
	(regcache::write_part): Rename to ...
	(register_readwriter::write_part): ... this.
	(readable_regcache::raw_read_part): Rename to ...
	(register_reader::raw_read_part): ... this, adjust.
	(regcache::raw_write_part): Rename to ...
	(register_readwriter::raw_write_part): ... this, adjust.
	(readable_regcache::cooked_read_part): Rename to ...
	(register_reader::cooked_read_part): ... this, adjust.
	(regcache::cooked_write_part): Rename to ...
	(register_readwriter::cooked_write_part): ... this, adjust.
	(reg_buffer::num_raw_registers):
	* aarch64-tdep.c (aarch64_pseudo_read_value_1): Use
	register_reader/register_readwriter.
	(aarch64_pseudo_read_value): Likewise.
	(aarch64_pseudo_write_1): Likewise.
	(aarch64_pseudo_write): Likewise.
	* amd64-tdep.c (amd64_pseudo_register_read_value): Likewise.
	(amd64_pseudo_register_write): Likewise.
	* arm-tdep.c (arm_neon_quad_read): Likewise.
	(arm_neon_quad_write): Likewise.
	(arm_pseudo_read): Likewise.
	(arm_pseudo_write): Likewise.
	* avr-tdep.c (avr_pseudo_register_read): Likewise.
	(avr_pseudo_register_write): Likewise.
	* bfin-tdep.c (bfin_pseudo_register_read): Likewise.
	(bfin_pseudo_register_write): Likewise.
	* frv-tdep.c (frv_pseudo_register_read): Likewise.
	(frv_pseudo_register_write): Likewise.
	* gdbarch.sh (gdbarch_pseudo_register_read,
	gdbarch_pseudo_register_read_value): Use register_reader.
	(gdbarch_pseudo_register_write): Use register_readwriter.
	* gdbarch.c: Re-generate.
	* gdbarch.h: Re-generate.
	* h8300-tdep.c (pseudo_from_raw_register): Likewise.
	(raw_from_pseudo_register): Likewise.
	(h8300_pseudo_register_read): Likewise.
	(h8300_pseudo_register_write): Likewise.
	* hppa-tdep.c (hppa_pseudo_register_read): Likewise.
	* i386-tdep.c (i386_mmx_regnum_to_fp_regnum): Likewise.
	(i386_pseudo_register_read_into_value): Likewise.
	(i386_pseudo_register_read_value): Likewise.
	(i386_pseudo_register_write): Likewise.
	* i386-tdep.h (i386_pseudo_register_read_into_value): Likewise.
	(i386_pseudo_register_write): Likewise.
	* ia64-libunwind-tdep.c (libunwind_get_reg_special): Likewise.
	* ia64-libunwind-tdep.h (libunwind_get_reg_special): Likewise.
	* ia64-tdep.c (ia64_pseudo_register_read): Likewise.
	(ia64_pseudo_register_write): Likewise.
	* m32c-tdep.c (register_status): Likewise.
	(m32c_raw_read): Likewise.
	(m32c_raw_write): Likewise.
	(m32c_read_flg): Likewise.
	(m32c_banked_register): Likewise.
	(m32c_banked_read): Likewise.
	(m32c_banked_write): Likewise.
	(m32c_sb_read): Likewise.
	(m32c_sb_write): Likewise.
	(m32c_part_read): Likewise.
	(m32c_part_write): Likewise.
	(m32c_cat_read): Likewise.
	(m32c_cat_write): Likewise.
	(m32c_r3r2r1r0_read): Likewise.
	(m32c_r3r2r1r0_write): Likewise.
	(m32c_pseudo_register_read): Likewise.
	(m32c_pseudo_register_write): Likewise.
	* m68hc11-tdep.c (m68hc11_pseudo_register_read): Likewise.
	(m68hc11_pseudo_register_write): Likewise.
	* mep-tdep.c (mep_pseudo_cr32_read): Likewise.
	(mep_pseudo_cr64_read): Likewise.
	(mep_pseudo_register_read): Likewise.
	(mep_pseudo_csr_write): Likewise.
	(mep_pseudo_cr32_write): Likewise.
	(mep_pseudo_cr64_write): Likewise.
	(mep_pseudo_register_write): Likewise.
	* mips-tdep.c (mips_pseudo_register_read): Likewise.
	(mips_pseudo_register_write): Likewise.
	* msp430-tdep.c (msp430_pseudo_register_read): Likewise.
	(msp430_pseudo_register_write): Likewise.
	* nds32-tdep.c (nds32_pseudo_register_read): Likewise.
	(nds32_pseudo_register_write): Likewise.
	* rl78-tdep.c (rl78_pseudo_register_read): Likewise.
	(rl78_pseudo_register_write): Likewise.
	* rs6000-tdep.c (e500_move_ev_register): Likewise.
	(do_regcache_raw_write): Likewise.
	(e500_pseudo_register_read): Likewise.
	(e500_pseudo_register_write): Likewise.
	(dfp_pseudo_register_read): Likewise.
	(dfp_pseudo_register_write): Likewise.
	(v_alias_pseudo_register_read): Likewise.
	(v_alias_pseudo_register_write): Likewise.
	(vsx_pseudo_register_read): Likewise.
	(vsx_pseudo_register_write): Likewise.
	(efp_pseudo_register_read): Likewise.
	(efp_pseudo_register_write): Likewise.
	(rs6000_pseudo_register_read): Likewise.
	(rs6000_pseudo_register_write): Likewise.
	* s390-tdep.c (s390_pseudo_register_read): Likewise.
	(s390_pseudo_register_write): Likewise.
	* sh-tdep.c (pseudo_register_read_portions): Likewise.
	(sh_pseudo_register_read): Likewise.
	(sh_pseudo_register_write): Likewise.
	* sparc-tdep.c (sparc32_pseudo_register_read): Likewise.
	(sparc32_pseudo_register_write): Likewise.
	* sparc64-tdep.c (sparc64_pseudo_register_read): Likewise.
	(sparc64_pseudo_register_write): Likewise.
	* spu-tdep.c (spu_pseudo_register_read_spu): Likewise.
	(spu_pseudo_register_read): Likewise.
	(spu_pseudo_register_write_spu): Likewise.
	(spu_pseudo_register_write): Likewise.
	* xtensa-tdep.c (xtensa_register_write_masked): Likewise.
	(xtensa_register_read_masked): Likewise.
	(xtensa_pseudo_register_read): Likewise.
	(xtensa_pseudo_register_write): Likewise.