amd64 g++ 4.4 fix: Merge enum amd64_syscall and enum amd64_x32_syscall
Build fails with g++ 4.4:

/home/emaisin/src/binutils-gdb/gdb/amd64-linux-tdep.c: In function ‘gdb_syscall amd64_canonicalize_syscall(amd64_syscall)’:
/home/emaisin/src/binutils-gdb/gdb/amd64-linux-tdep.c:369: error: case label value exceeds maximum value for type
/home/emaisin/src/binutils-gdb/gdb/amd64-linux-tdep.c:373: error: case label value exceeds maximum value for type

This is because the switch is done on a variable of type enum
amd64_syscall but the case labels are a mix from enum amd64_syscall and
enum amd64_x32_syscall.

The simple but clean solution I found is to merge those enum definitions in a
single enum.  Another solution would be to assign the enum value to an
int, and then switch on that int.