ctf g++ 4.4 fix: Use macro for format string instead of variable
g++ 4.4 is not clever enough to deduce that metadata_fmt is always a
literal string.  Therefore, define the string in a macro instead of
assigning it to a const char[].

Fixes:

/home/emaisin/src/binutils-gdb/gdb/ctf.c: In function ‘void ctf_save_metadata_header(trace_write_handler*)’:
/home/emaisin/src/binutils-gdb/gdb/ctf.c:267: error: format not a string literal, argument types not checked